version: '3.8'

services:
  fes01:
    image: ghcr.io/prathamadh/prashnakhoj:v1
    # ports:
    #   - "8080:8080"
    networks:
      - elastic

  # kibana:
  #   image: depkibana:v1
  #   networks:
  #     - elastic
  #   ports:
  #     - "5601:5601"

  fbackend:
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - elastic

  ffrontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
