version: '3.8'

services:
  es01:
    image: depelastic:v1
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: depkibana:v1
    networks:
      - elastic
    ports:
      - "5601:5601"

networks:
  elastic:
    driver: bridge


